version: '3.8'

services:
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - '8084:80'
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - main
    tty: true
    links:
      - app

  app:
    container_name: app
    build:
      context: ./docker/php
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '9000:9000'
    working_dir:
      /var/www/app
    volumes:
      - ./app:/var/www/app
      - ./docker/php/settings/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - main
    env_file:
      - .env
    restart: always
    tty: true

  pgsql:
    image: postgres:14-alpine
    env_file:
      - .env
    restart: always
    networks:
      - main
    expose:
      - 5432
    ports:
      - "5432:5432"

networks:
  main:
    external: false